name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main  # of de branch waar je wijzigingen op doorvoert

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
      - uses: actions/checkout@v4          # haalt hele repo op
        with: { fetch-depth: 0 }
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Of de Node.js versie die je nodig hebt
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build                      # map met statische bestanden
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
